export const FEELINGS = {
  MET: {
    AFFECTIONATE: { id: "AFFECTIONATE", name: "Affectionate", emoji: "😍" },
    CONFIDENT: { id: "CONFIDENT", name: "Confident", emoji: "😎" },
    ENGAGED: { id: "ENGAGED", name: "Engaged", emoji: "🤩" },
    EXCITED: { id: "EXCITED", name: "Excited", emoji: "🤪" },
    EXHILARATED: { id: "EXHILARATED", name: "Exhilarated", emoji: "😃" },
    GRATEFUL: { id: "GRATEFUL", name: "Grateful", emoji: "🥰" },
    HOPEFUL: { id: "HOPEFUL", name: "Hopeful", emoji: "🤗" },
    JOYFUL: { id: "JOYFUL", name: "Joyful", emoji: "😂" },
    INSPIRED: { id: "INSPIRED", name: "Inspired", emoji: "🥲" },
    PEACEFUL: { id: "PEACEFUL", name: "Peaceful", emoji: "😌" },
    REFRESHED: { id: "REFRESHED", name: "Refreshed", emoji: "😊" },
  },
  NOT_MET: {
    AFRAID: { id: "AFRAID", name: "Afraid", emoji: "😨" },
    ANNOYED: { id: "ANNOYED", name: "Annoyed", emoji: "😒" },
    ANGRY: { id: "ANGRY", name: "Angry", emoji: "😡" },
    AVERSION: { id: "AVERSION", name: "Aversion", emoji: "😖" },
    CONFUSED: { id: "CONFUSED", name: "Confused", emoji: "🤔" },
    DISCONNECTED: { id: "DISCONNECTED", name: "Disconnected", emoji: "😔" },
    DISQUIET: { id: "DISQUIET", name: "Disquiet", emoji: "🫨" },
    EMBARRASSED: { id: "EMBARRASSED", name: "Embarrassed", emoji: "😳" },
    FATIGUED: { id: "FATIGUED", name: "Fatigued", emoji: "🥱" },
    PAIN: { id: "PAIN", name: "Pain", emoji: "😣" },
    SAD: { id: "SAD", name: "Sad", emoji: "😢" },
    TENSE: { id: "TENSE", name: "Tense", emoji: "😬" },
    VULNERABLE: { id: "VULNERABLE", name: "Vulnerable", emoji: "😰" },
    YEARNING: { id: "YEARNING", name: "Yearning", emoji: "🥺" },
  },
};

export const SIMILAR_FEELINGS = {
  AFFECTIONATE: [
    "affectionate",
    "compassionate",
    "fond",
    "loving",
    "openhearted",
    "tender",
    "warm",
  ],
  CONFIDENT: ["empowered", "confident", "open", "proud", "safe", "secure"],
  ENGAGED: [
    "absorbed",
    "curious",
    "engaged",
    "engrossed",
    "enchanted",
    "enthralled",
    "entranced",
    "fascinated",
    "interested",
    "intrigued",
    "involved",
    "open",
    "spellbound",
    "stimulated",
  ],
  EXCITED: [
    "amazed",
    "ardent",
    "aroused",
    "dazzled",
    "energetic",
    "enlivened",
    "enthusiastic",
    "excited",
    "exuberant",
    "invigorated",
    "lively",
    "passionate",
    "surprised",
    "vibrant",
  ],
  EXHILARATED: [
    "enthralled",
    "exhilerated",
    "radiant",
    "electrified",
    "euphoric",
    "overjoyed",
    "thrilled",
  ],
  GRATEFUL: ["appreciative", "moved", "thankful", "touched"],
  JOYFUL: [
    "amused",
    "blissful",
    "cheerful",
    "delighted",
    "ecstatic",
    "elated",
    "giddy",
    "glad",
    "jolly",
    "joyful",
    "jubilant",
    "merry",
    "overjoyed",
    "pleased",
    "rapturous",
    "tickled",
  ],
  HOPEFUL: [
    "confident",
    "expectant",
    "hopeful",
    "jazzed",
    "lighthearted",
    "sanguine",
    "up",
    "upbeat",
  ],
  INSPIRED: [
    "amazed",
    "eager",
    "enthused",
    "inspired",
    "motivated",
    "moved",
    "psyched",
    "stimulated",
    "stirred",
    "wonder",
  ],
  PEACEFUL: [
    "calm",
    "comfortable",
    "centered",
    "content",
    "equanimity",
    "fulfilled",
    "mellow",
    "open",
    "peaceful",
    "quiet",
    "relaxed",
    "relieved",
    "satisfied",
    "serene",
    "tranquil",
  ],
  REFRESHED: ["recharged", "refreshed", "rejuvenated", "renewed", "rested", "restored", "revived"],

  ANGRY: [
    "aggravated",
    "angry",
    "animosity",
    "annoyed",
    "contempt",
    "disgruntled",
    "enraged",
    "exasperated",
    "furious",
    "hate",
    "hostile",
    "incensed",
    "irate",
    "irritated",
    "irked",
    "livid",
    "miffed",
    "nettled",
    "outraged",
    "peeved",
    "resentful",
  ],
  ANNOYED: [
    "aggravated",
    "annoyed",
    "dismayed",
    "disgruntled",
    "displeased",
    "exasperated",
    "frustrated",
    "impatient",
    "irritated",
    "irked",
  ],
  AVERSION: [
    "abhorrence",
    "appalled",
    "aversion",
    "bothered",
    "displeased",
    "disgust",
    "dislike",
    "enmity",
    "horrified",
    "loathing",
    "repulsion",
    "revulsion",
  ],
  CONFUSED: [
    "ambivalent",
    "baffled",
    "bewildered",
    "conflicted",
    "confused",
    "dazed",
    "discombobulated",
    "disoriented",
    "mixed",
    "mystified",
    "perplexed",
    "puzzled",
    "torn",
  ],
  DISCONNECTED: [
    "apathetic",
    "bored",
    "closed",
    "detached",
    "disconnected",
    "distant",
    "indifferent",
    "listless",
    "numb",
    "withdrawn",
  ],
  DISQUIET: [
    "agitated",
    "alarmed",
    "concerned",
    "distraught",
    "disconcerted",
    "dismayed",
    "disquieted",
    "disturbed",
    "frustrated",
    "perturbed",
    "rattled",
    "restless",
    "shocked",
    "startled",
    "surprised",
    "troubled",
    "turbulent",
    "turmoil",
    "uncomfortable",
    "uneasy",
    "unnerved",
    "unsettled",
    "upset",
  ],
  EMBARRASSED: [
    "ashamed",
    "chagrined",
    "discomfited",
    "flustered",
    "embarassed",
    "mortified",
    "self-conscious",
  ],
  FATIGUED: [
    "beat",
    "burnt out",
    "fatigued",
    "depleted",
    "exhausted",
    "listless",
    "pooped",
    "sleepy",
    "tired",
    "weary",
    "wiped out",
    "worn out",
  ],
  AFRAID: [
    "afraid",
    "anxious",
    "apprehensive",
    "dread",
    "fearful",
    "foreboding",
    "frightened",
    "guarded",
    "insecure",
    "leery",
    "mistrustful",
    "panicked",
    "petrified",
    "scared",
    "shaky",
    "terrified",
    "trepidation",
    "wary",
    "worried",
  ],
  PAIN: [
    "aching",
    "agony",
    "anguished",
    "devastated",
    "grief",
    "heartbroken",
    "hungry",
    "hurting",
    "lonely",
    "miserable",
    "pain",
    "regretful",
    "remorseful",
  ],
  SAD: [
    "depressed",
    "dejected",
    "despairing",
    "despondent",
    "disappointed",
    "discouraged",
    "disheartened",
    "forlorn",
    "gloomy",
    "heavy hearted",
    "hopeless",
    "melancholy",
    "miserable",
    "sad",
    "unhappy",
    "wistful",
  ],
  TENSE: [
    "anxious",
    "closed",
    "distressed",
    "edgy",
    "fidgety",
    "frazzled",
    "frustrated",
    "jittery",
    "nervous",
    "overwhelmed",
    "restless",
    "stressed out",
    "tense",
  ],
  YEARNING: ["longing", "nostalgic", "pining", "yearning"],
  VULNERABLE: [
    "vulnerable",
    "fragile",
    "guarded",
    "helpless",
    "insecure",
    "leery",
    "reserved",
    "sensitive",
    "shaky",
  ],
};
